---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbtt-deployment
  labels:
    app: tbtt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tbtt
  template:
    metadata:
      labels:
        app: tbtt
    spec:
      containers:
        - name: tbtt
          image: tbtt-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tbtt-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tbtt
  type: LoadBalancer